version: "3.9"

services:
  loadbalancer:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: loadbalancer
    ports:
      - "5000:5000"
    networks:
      - lb-network
    depends_on:
      - testserver1
      - testserver2

  testserver1:
    build:
      context: ../TestApplications/TestServer/TestServer
      dockerfile: Dockerfile
    container_name: testserver1
    hostname: testserver1
    environment:
      - ServerId=1
    ports:
      - "5001:8080"
    networks:
      - lb-network

  testserver2:
    build:
      context: ../TestApplications/TestServer/TestServer
      dockerfile: Dockerfile
    container_name: testserver2
    hostname: testserver2
    environment:
      - ServerId=2
    ports:
      - "5002:8080"
    networks:
      - lb-network

networks:
  lb-network:
    driver: bridge
